// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Tue Mar 30 11:31:52 2021

test test_inst
(
	.pin_name1(pin_name1_sig) ,	// output  pin_name1_sig
	.pin_name2(pin_name2_sig) ,	// output  pin_name2_sig
	.pin_name3(pin_name3_sig) ,	// output  pin_name3_sig
	.pin_name4(pin_name4_sig) ,	// output  pin_name4_sig
	.pin_name5(pin_name5_sig) ,	// output  pin_name5_sig
	.pin_name6(pin_name6_sig) ,	// output  pin_name6_sig
	.pin_name7(pin_name7_sig) ,	// output  pin_name7_sig
	.pin_name8(pin_name8_sig) 	// output  pin_name8_sig
);

